sudo: required
dist: trusty
env:
  - GOPATH=$HOME
  
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpcap-dev
  - go get github.com/anastop/latte

  
script: 
  - go build github.com/anastop/latte
  - go test -v github.com/anastop/latte/matching
